### ISSUE TITLE
Docker image is not working: kustomize is missing

### ISSUE THREAD

**Issue by timcooijmans** [nekottyo/docker-kustomize-kubeval#1]
Hi,

Your docker image is not working: Downloading of kustomize failed with http-status-code 404 when building the image. As a result the kustomize "binary" contains "Not Found".

**Comment by mauricio-ryan** [comment]
same happened to me, please fix it

**Comment by pablothx** [comment]
We are running into the same issue as well. Please check it out as soon as possible.
Thanks!

**Comment by nekottyo** [comment]
Hi,
Sorry for the late response.

Kustomize's download url was changed.
Fixed by https://github.com/nekottyo/docker-kustomize-kubeval/issues/2
