### ISSUE TITLE
No image tags

### ISSUE THREAD

**Issue by drewfreyling** [nekottyo/docker-kustomize-kubeval#18]
The recent kustomize v4 upgrade of the docker image had some breaking changes around the `load-restrictor` flag. Are we able to get image tags added for this repo so we don't get hit by breaking changes because we are only allowed to use the latest tag.

**Comment by nekottyo** [comment]
@drewfreyling Hi.
I create images of `nekottyo/kustomize-kubeval:kustomizev3` and `nekottyo/kustomize-kubeval:kustomizev4`.
Dit that problem get solved?
```
❯ docker run --rm nekottyo/kustomize-kubeval:kustomizev3 kustomize version
{Version:kustomize/v3.10.0 GitCommit:602ad8aa98e2e17f6c9119e027a09757e63c8bec BuildDate:2021-02-10T00:00:50Z GoOs:linux GoArch:amd64}
```
```
❯ docker run --rm nekottyo/kustomize-kubeval:kustomizev4 kustomize version
{Version:kustomize/v4.2.0 GitCommit:d53a2ad45d04b0264bcee9e19879437d851cb778 BuildDate:2021-06-30T22:49:26Z GoOs:linux GoArch:amd64}
```
